### ISSUE TITLE
13.classes or assignments with the same name should not be allowed

### ISSUE THREAD

**Issue by okoo** [dschinde/homework-organizer#31]

**Comment by klongtran** [comment]
There should be a gentle error message if he/she tries entering a duplicate class/assignment name

**Comment by dschinde** [comment]
I think that assignments with the same name should be allowed.

"Read Ch. 13" isn't really all that limiting.

**Comment by klongtran** [comment]
That's true! So just avoid same classes name then.

**Comment by klongtran** [comment]
Issue solved. Classes with same name are not allowed, but assignments are.
