### ISSUE TITLE
Classes don't work correctly immediately after being created

### ISSUE THREAD

**Issue by clarah2** [dschinde/homework-organizer#40]
Steps to reproduce:
1. add a new class
2. click on the class from class list
3. went to "All Assignments" screen, should have gone to specific class screen

After this, I quit the app and when i reopened it, clicking on the class worked correctly.

**Comment by clarah2** [comment]
Hey @dschinde 
Do you see this bug also? I didnt notice this on your phone in class but this has been a consistent problem for me all afternoon.

**Comment by dschinde** [comment]
I see it. I'll fix it.

**Comment by clarah2** [comment]
I have been working with Paul on it. I have one edit to push but am not at
my computer at the moment. But it seems to be better, maybe?

**Comment by clarah2** [comment]
had left out a semicolon, but it's definitely not working, so yeah, go for it @dschinde

**Comment by dschinde** [comment]
Fixed
